'use strict';
angular.module('dashboard',[
	'ngAnimate',
    'ngCookies',
    'ngMessages',
    'ngResource',
	'ui.router',
	'ui.bootstrap'
	])
.config(function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('/login');
	$stateProvider
	 	.state('login',{
			url:'/login',
			templateUrl:'templates/login.html',
			controller:'loginController'
		})
		.state('root',{
			url:'/root',
			templateUrl:'templates/root.html',
			controller:'rootController',
			abstract:true
		})
		.state('root.work',{
			url:'/work',
			templateUrl:'templates/work.html',
			controller:'workController'
		})
		.state('root.overview',{
			url:'/overview',
			templateUrl:'templates/overview.html',
			controller:'overviewController'
		})
		.state('root.producer',{
			url:'/producer',
			templateUrl:'templates/producer.html',
			controller:'producerController'
		})
		.state('root.contact',{
			url:'contact',
			templateUrl:'templates/contact.html',
			controller:'contactController'
		});
});